AWSTemplateFormatVersion: '2010-09-09'
Resources:
  BackupVault:
    Type: "AWS::Backup::BackupVault"
    Properties:
      BackupVaultName: "SMSBASELINE-BackupVault"

  BackupPlan:
    Type: "AWS::Backup::BackupPlan"
    Properties:
      BackupPlan:
        BackupPlanName: "SMSBASELINE-BackupVault"
        BackupPlanRule:
          - RuleName: "SMSBASELINE-RuleForDailyBackups"
            TargetBackupVault: !Ref BackupVault
            ScheduleExpression: "cron(0 5 ? * * *)"

  BackupSelection:
    Type: "AWS::Backup::BackupSelection"
    Properties:
      BackupSelection:
        SelectionName: SMSBASELINE-BackupSelection
        IamRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-controltower-SMSBASELINE-BackupRole"
        ListOfTags:
          - ConditionType: "STRINGEQUALS"
            ConditionKey: "SMSBASELINE-Backup"
            ConditionValue: "daily"
      BackupPlanId: !Ref BackupPlan